// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knyugfafvvwjbeqdrlka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtueXVnZmFmdnZ3amJlcWRybGthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5OTAwNzMsImV4cCI6MjA1MjU2NjA3M30.EHLsQmd2KxikVqoBj2SYrrXIaUJ-7Uu2mSY6enzEEgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);